### ISSUE TITLE
module.h does not exist

### ISSUE THREAD

**Issue by vishneak** [cavaliercoder/zabbix-module-sockets#5]
Hello,
I want to test this module on my Zabbix server installed with apt on a Ubuntu machine (zabbix_server (Zabbix) 3.2.7).
I can see a *.rpm package for yum and a *.tar.gz archive on the code page. I have downloaded  the tar.gz on Zabbix server and unpacked it.  When running ./configure command i am getting configure: error: /etc/zabbix//include/module.h does not exist. 
Please, let me know how do I handle this.

**Comment by cavaliercoder** [comment]
You'll also need the Zabbix source code tarball. Then tell configure where you have extracted them to:
```
$ ./configure --with-zabbix=<source-location>
```

**Comment by vishneak** [comment]
Thanks! that worked like a charm. 
It have passed more than 1.5 hours but this table is still empty: https://ibb.co/h8uTda
Are you aware where the issue might be?

**Comment by cavaliercoder** [comment]
There's all sorts of things that could be wrong. Do the items appear to be supported? Can the agent reach the server for active checks? Are there any errors in the server or agent logs?
