### ISSUE TITLE
Data not match with netstat

### ISSUE THREAD

**Issue by ankujuniyal** [cavaliercoder/zabbix-module-sockets#9]
In netstat
netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      2045/mongod
tcp        0      0 0.0.0.0:3306         0.0.0.0:*               LISTEN      8789/mongosqld
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1513/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1726/master
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN      43154/zabbix_agentd

while in ss
ss -tl
State      Recv-Q Send-Q                                                       Local Address:Port                                                                        Peer Address:Port
LISTEN     0      128                                                                      *:27017                                                                                  *:*
LISTEN     0      8192                                                           *:mysql                                                                                  *:*
LISTEN     0      128                                                                      *:ssh                                                                                    *:*
LISTEN     0      100                                                              127.0.0.1:smtp                                                                                   *:*
LISTEN     0      128                                                                      *:10050                                                                                  *:*

In in zabbix value is diff.  
<img width="1273" alt="Screenshot 2020-08-06 at 7 06 40 PM" src="https://user-images.githubusercontent.com/4637422/89538294-013fe200-d818-11ea-8b37-9b2e949b6d37.png">

**Comment by cavaliercoder** [comment]
I don't see the issue. Can you please clarify? You ss and netstat samples only appear to include LISTEN sockets. The zabbix graph shows the sum of all sockets.

**Comment by ankujuniyal** [comment]
yes, then how to get listen socket send or receive using zabbix.

**Comment by ankujuniyal** [comment]
@cavaliercoder  sorry my bad, i was using key sockets.recvq[tcp] in zabbix and on server i was checking data  netstat -tnlp that is why recv-Q data was diff, I forgot to add sockets.recvq[tcp,LISTEN].
Thats man.
